defmodule Tunez.Repo.Migrations.AddUniqueAlbumNamesPerArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:albums, [:name, :artist_id],
             name: "albums_unique_album_names_per_artist_index"
           )
  end

  def down do
    drop_if_exists unique_index(:albums, [:name, :artist_id],
                     name: "albums_unique_album_names_per_artist_index"
                   )
  end
end

# to apply, 'mix ash.migrate'

# Create an album
# with a specific name, and then try to create another one for the same artist
# with the same name — you should get a validation error on the name field,
# with the message we specified for the identity.
